# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controls.ui'
#
# Created: Sun Oct 09 17:07:42 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Controls_MainWindow(object):
    def setupUi(self, Controls_MainWindow):
        Controls_MainWindow.setObjectName(_fromUtf8("Controls_MainWindow"))
        Controls_MainWindow.resize(844, 418)
        Controls_MainWindow.setWindowTitle(QtGui.QApplication.translate("Controls_MainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(Controls_MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.frame_6 = QtGui.QFrame(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(242, 0))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.paramView = QtGui.QScrollArea(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramView.sizePolicy().hasHeightForWidth())
        self.paramView.setSizePolicy(sizePolicy)
        self.paramView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.paramView.setWidgetResizable(True)
        self.paramView.setObjectName(_fromUtf8("paramView"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 238, 376))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.paramView.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.paramView)
        self.frame_5 = QtGui.QFrame(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.splitter_2 = QtGui.QSplitter(self.frame_5)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame_3 = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter_4 = QtGui.QSplitter(self.frame_3)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(4)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.frame = QtGui.QFrame(self.splitter_4)
        self.frame.setMinimumSize(QtCore.QSize(0, 22))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter = QtGui.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Controls_MainWindow", "New filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.filter_list = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_list.sizePolicy().hasHeightForWidth())
        self.filter_list.setSizePolicy(sizePolicy)
        self.filter_list.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.filter_list.setAlternatingRowColors(False)
        self.filter_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.filter_list.setObjectName(_fromUtf8("filter_list"))
        self.verticalLayout_3.addWidget(self.filter_list)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Controls_MainWindow", "Saved filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.saved_filter_list = QtGui.QListWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saved_filter_list.sizePolicy().hasHeightForWidth())
        self.saved_filter_list.setSizePolicy(sizePolicy)
        self.saved_filter_list.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saved_filter_list.setModelColumn(0)
        self.saved_filter_list.setWordWrap(False)
        self.saved_filter_list.setObjectName(_fromUtf8("saved_filter_list"))
        self.verticalLayout_2.addWidget(self.saved_filter_list)
        self.horizontalLayout_3.addWidget(self.splitter)
        self.frame_2 = QtGui.QFrame(self.splitter_4)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 180))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.total_time_label = QtGui.QLabel(self.frame_2)
        self.total_time_label.setText(QtGui.QApplication.translate("Controls_MainWindow", "Sum:", None, QtGui.QApplication.UnicodeUTF8))
        self.total_time_label.setObjectName(_fromUtf8("total_time_label"))
        self.horizontalLayout_2.addWidget(self.total_time_label)
        self.limit_fps_label = QtGui.QLabel(self.frame_2)
        self.limit_fps_label.setToolTip(QtGui.QApplication.translate("Controls_MainWindow", "Set to zero for no limitation. ", None, QtGui.QApplication.UnicodeUTF8))
        self.limit_fps_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.limit_fps_label.setText(QtGui.QApplication.translate("Controls_MainWindow", "Limit fps to", None, QtGui.QApplication.UnicodeUTF8))
        self.limit_fps_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.limit_fps_label.setObjectName(_fromUtf8("limit_fps_label"))
        self.horizontalLayout_2.addWidget(self.limit_fps_label)
        self.fps_limit_spin = QtGui.QDoubleSpinBox(self.frame_2)
        self.fps_limit_spin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.fps_limit_spin.setSpecialValueText(QtGui.QApplication.translate("Controls_MainWindow", "No limit", None, QtGui.QApplication.UnicodeUTF8))
        self.fps_limit_spin.setAccelerated(False)
        self.fps_limit_spin.setPrefix(_fromUtf8(""))
        self.fps_limit_spin.setSuffix(_fromUtf8(""))
        self.fps_limit_spin.setDecimals(1)
        self.fps_limit_spin.setMaximum(200.0)
        self.fps_limit_spin.setSingleStep(1.0)
        self.fps_limit_spin.setObjectName(_fromUtf8("fps_limit_spin"))
        self.horizontalLayout_2.addWidget(self.fps_limit_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tree_filters_in_scene = QtGui.QTreeWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tree_filters_in_scene.sizePolicy().hasHeightForWidth())
        self.tree_filters_in_scene.setSizePolicy(sizePolicy)
        self.tree_filters_in_scene.setProperty("showDropIndicator", False)
        self.tree_filters_in_scene.setDragEnabled(False)
        self.tree_filters_in_scene.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tree_filters_in_scene.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tree_filters_in_scene.setRootIsDecorated(False)
        self.tree_filters_in_scene.setItemsExpandable(False)
        self.tree_filters_in_scene.setHeaderHidden(False)
        self.tree_filters_in_scene.setExpandsOnDoubleClick(False)
        self.tree_filters_in_scene.setObjectName(_fromUtf8("tree_filters_in_scene"))
        self.tree_filters_in_scene.headerItem().setText(0, QtGui.QApplication.translate("Controls_MainWindow", "Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_filters_in_scene.headerItem().setText(1, QtGui.QApplication.translate("Controls_MainWindow", "Filter in scene", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_filters_in_scene.header().setDefaultSectionSize(50)
        self.tree_filters_in_scene.header().setSortIndicatorShown(True)
        self.verticalLayout_4.addWidget(self.tree_filters_in_scene)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.framePause = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePause.sizePolicy().hasHeightForWidth())
        self.framePause.setSizePolicy(sizePolicy)
        self.framePause.setMinimumSize(QtCore.QSize(60, 0))
        self.framePause.setText(QtGui.QApplication.translate("Controls_MainWindow", "Start/Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.framePause.setObjectName(_fromUtf8("framePause"))
        self.horizontalLayout.addWidget(self.framePause)
        self.frameAgain = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAgain.sizePolicy().hasHeightForWidth())
        self.frameAgain.setSizePolicy(sizePolicy)
        self.frameAgain.setMinimumSize(QtCore.QSize(32, 0))
        self.frameAgain.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameAgain.setText(QtGui.QApplication.translate("Controls_MainWindow", "Again", None, QtGui.QApplication.UnicodeUTF8))
        self.frameAgain.setObjectName(_fromUtf8("frameAgain"))
        self.horizontalLayout.addWidget(self.frameAgain)
        self.frameNext = QtGui.QPushButton(self.frame_2)
        self.frameNext.setMinimumSize(QtCore.QSize(32, 0))
        self.frameNext.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameNext.setText(QtGui.QApplication.translate("Controls_MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.frameNext.setObjectName(_fromUtf8("frameNext"))
        self.horizontalLayout.addWidget(self.frameNext)
        self.restartButton = QtGui.QPushButton(self.frame_2)
        self.restartButton.setMinimumSize(QtCore.QSize(44, 0))
        self.restartButton.setText(QtGui.QApplication.translate("Controls_MainWindow", "Restart", None, QtGui.QApplication.UnicodeUTF8))
        self.restartButton.setObjectName(_fromUtf8("restartButton"))
        self.horizontalLayout.addWidget(self.restartButton)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.status_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(90)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setText(QtGui.QApplication.translate("Controls_MainWindow", "Status: Paused", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.verticalLayout_4.addWidget(self.status_label)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addWidget(self.splitter_4)
        self.frame_4 = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.addedFilters_view = QtGui.QGraphicsView(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.addedFilters_view.sizePolicy().hasHeightForWidth())
        self.addedFilters_view.setSizePolicy(sizePolicy)
        self.addedFilters_view.setMinimumSize(QtCore.QSize(100, 100))
        self.addedFilters_view.setObjectName(_fromUtf8("addedFilters_view"))
        self.verticalLayout_6.addWidget(self.addedFilters_view)
        self.verticalLayout_5.addWidget(self.splitter_2)
        self.horizontalLayout_5.addWidget(self.splitter_3)
        self.horizontalLayout_5.setStretch(0, 1)
        Controls_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Controls_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Controls_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Controls_MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Controls_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Controls_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Controls_MainWindow)

    def retranslateUi(self, Controls_MainWindow):
        self.tree_filters_in_scene.setSortingEnabled(True)

